name: 'setup-job-workspacce-action'
description: 'A action create workspace to checkout repository for each jobs'
author: 'kesin1202000@gmail.com'
inputs:
  workspace-name:
    required: false
    description: 'Input workspace directory name if you need to change from default: ${workspace-yaml-name}-${job-name}'
  repository-name:
    required: false
    description: 'Set repository name for workspace directory path. default: ""'
    default: ""
  prefix:
    required: false
    description: 'Set prefix for workspace directory name. default: ""'
    default: ""
  suffix:
    required: false
    description: 'Set suffix for workspace directory name. default: ""'
    default: ""
  working-directory:
    required: false
    description: 'Set working-directory for nodejs. default: "" (Linux, macOS), ".." (Windows)'
    default: "${{ runner.os == 'Windows' && '..' || '' }}"
runs:
  using: 'node24'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
