name: 'Actions integrate test'
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  default_name:
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    steps:
      - name: $GITHUB_WORKSPACE is not symlink
        run: |
          if [ -L $GITHUB_WORKSPACE ]; then
            exit 1
          fi

      - uses: actions/checkout@v3
      - uses: ./

      - name: $GITHUB_WORKSPACE is symlink
        run: test -L $GITHUB_WORKSPACE
      - name: $GITHUB_WORKSPACE.bak is exists 
        run: test -d ${GITHUB_WORKSPACE}.bak
      - name: Created workspace is not symlkink
        # Default dir name: ${YAML_NAME}-${JOB_NAME}
        run: |
          test -d $RUNNER_WORKSPACE/actions_integrate_test-default_name
          if [ -L $RUNNER_WORKSPACE/actions_integrate_test-default_name ]; then
            exit 1
          fi

      - name: Checkout to new workspace for action post process
        uses: actions/checkout@v3
        if: ${{ always() }}
  workspace_name:
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    steps:
      - name: $GITHUB_WORKSPACE is not symlink
        run: |
          if [ -L $GITHUB_WORKSPACE ]; then
            exit 1
          fi

      - uses: actions/checkout@v3
      - uses: ./
        with:
          workspace-name: test-dir

      - name: $GITHUB_WORKSPACE is symlink
        run: test -L $GITHUB_WORKSPACE
      - name: $GITHUB_WORKSPACE.bak is exists 
        run: test -d ${GITHUB_WORKSPACE}.bak
      - name: Created workspace is not symlkink
        run: |
          test -d $RUNNER_WORKSPACE/test-dir
          if [ -L $RUNNER_WORKSPACE/test-dir ]; then
            exit 1
          fi

      - name: Checkout to new workspace for action post process
        uses: actions/checkout@v3
        if: ${{ always() }}

  default_name_with_prefix_suffix:
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          prefix: "Prefix-"
          suffix: "-Suffix"

      - name: Created workspace is not symlkink
        # Default dir name: ${YAML_NAME}-${JOB_NAME}
        run: |
          test -d $RUNNER_WORKSPACE/prefix-actions_integrate_test-default_name-suffix
          if [ -L $RUNNER_WORKSPACE/prefix-actions_integrate_test-default_name-suffix ]; then
            exit 1
          fi

      - name: Checkout to new workspace for action post process
        uses: actions/checkout@v3
        if: ${{ always() }}
