name: "Actions integrate test"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  default_name:
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest, "windows-latest"]
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    steps:
      - name: $GITHUB_WORKSPACE is not symlink
        shell: bash
        run: |
          if [ -L $GITHUB_WORKSPACE ]; then
            exit 1
          fi

      - uses: actions/checkout@v3
      # Windows must chdir node.js current directory from mv target directory
      - uses: ./
        with:
          working-directory: "${{ runner.os == 'Windows' && '..' || '' }}"

      - name: $GITHUB_WORKSPACE is symlink
        shell: bash
        run: test -L $GITHUB_WORKSPACE
      - name: $GITHUB_WORKSPACE.bak is exists
        shell: bash
        run: test -d ${GITHUB_WORKSPACE}.bak
      - name: Created workspace is not symlkink
        shell: bash
        # Default dir name: ${workflow-yaml-name}-${job-name}
        run: |
          set -x
          ls -l $RUNNER_WORKSPACE
          test -d $RUNNER_WORKSPACE/actions-test-default_name
          if [ -L $RUNNER_WORKSPACE/actions-test-default_name ]; then
            exit 1
          fi

      - name: Checkout to new workspace for action post process
        uses: actions/checkout@v3
        if: ${{ always() }}

  workspace_name:
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest, "windows-latest"]
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    steps:
      - name: $GITHUB_WORKSPACE is not symlink
        shell: bash
        run: |
          set -x
          if [ -L $GITHUB_WORKSPACE ]; then
            exit 1
          fi

      - uses: actions/checkout@v3
      # Windows must chdir node.js current directory from mv target directory
      - uses: ./
        with:
          workspace-name: test-dir
          working-directory: "${{ runner.os == 'Windows' && '..' || '' }}"

      - name: $GITHUB_WORKSPACE is symlink
        shell: bash
        run: test -L $GITHUB_WORKSPACE
      - name: $GITHUB_WORKSPACE.bak is exists
        shell: bash
        run: test -d ${GITHUB_WORKSPACE}.bak
      - name: Created workspace is not symlkink
        shell: bash
        run: |
          set -x
          ls -l $RUNNER_WORKSPACE
          test -d $RUNNER_WORKSPACE/test-dir
          if [ -L $RUNNER_WORKSPACE/test-dir ]; then
            exit 1
          fi

      - name: Checkout to new workspace for action post process
        uses: actions/checkout@v3
        if: ${{ always() }}

  workspace_name_with_prefix_suffix:
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest, "windows-latest"]
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v3
      # Windows must chdir node.js current directory from mv target directory
      - uses: ./
        with:
          workspace-name: "test-dir"
          prefix: "Prefix-"
          suffix: "-Suffix"
          working-directory: "${{ runner.os == 'Windows' && '..' || '' }}"

      - name: Created workspace is not symlkin
        shell: bash
        run: |
          set -x
          ls -l $RUNNER_WORKSPACE
          test -d $RUNNER_WORKSPACE/prefix-test-dir-suffix
          if [ -L $RUNNER_WORKSPACE/prefix-test-dir-suffix ]; then
            exit 1
          fi

      - name: Checkout to new workspace for action post process
        uses: actions/checkout@v3
        if: ${{ always() }}

  working_directory:
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest, "windows-latest"]
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    steps:
      - name: $GITHUB_WORKSPACE is not symlink
        shell: bash
        run: |
          set -x
          if [ -L $GITHUB_WORKSPACE ]; then
            exit 1
          fi

      - uses: actions/checkout@v3
      - uses: ./
        with:
          working-directory: ".."

      - name: $GITHUB_WORKSPACE is symlink
        shell: bash
        run: test -L $GITHUB_WORKSPACE
      - name: $GITHUB_WORKSPACE.bak is exists
        shell: bash
        run: test -d ${GITHUB_WORKSPACE}.bak
      - name: Created workspace is not symlkink
        shell: bash
        # Default dir name: ${workflow-yaml-name}-${job-name}
        run: |
          set -x
          ls -l $RUNNER_WORKSPACE
          test -d $RUNNER_WORKSPACE/actions-test-working_directory
          if [ -L $RUNNER_WORKSPACE/actions-test-working_directory ]; then
            exit 1
          fi

      - name: Checkout to new workspace for action post process
        uses: actions/checkout@v3
        if: ${{ always() }}
