name: 'actions-test'
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: $GITHUB_WORKSPACE is not symlink
        run: |
          if [ -L $GITHUB_WORKSPACE ]; then
            exit 1
          fi

      - uses: actions/checkout@v3
      - uses: ./
        with:
          workspace-name: test-dir

      - name: $GITHUB_WORKSPACE is symlink
        run: test -L $GITHUB_WORKSPACE
      - name: $GITHUB_WORKSPACE.bak is exists 
        run: test -f ${GITHUB_WORKSPACE}.bak
      - name: Created workspace is not symlkink
        run: |
          test -f $RUNNER_WORKSPACE/test-dir
          if [ -L $RUNNER_WORKSPACE/test-dir ]; then
            exit 1
          fi
